[package]
name = "shimi"
version = "0.0.8"
edition = "2024"
authors = ["Shaked F."]

[[bin]]
name = "s"
path = "src/main.rs"

[features]
default = []
dry_run = []

[dependencies]
tap = { version = "1.0.1" } # Allows to tap/pipe/conv on any variable
itertools = { version = "0.14.0" } # Iterators and combinator

clap = { version = "4.5.17", features = ["derive", "cargo", "env", "string"] } # Handles parsing input from command line
ctrlc = { version = "3.4.7"} # Handles Ctrl+C signal

anyhow = { version = "1.0.97" } # Error handling
lazy_static = { version = "1.5.0" } # Lazy initialization of static variables

email_address = "0.2.9" # Validates email address
xdg-home = "1.3.0" # Gets the user's home directory

time = { version = "0.3.41", features = ["local-offset", "formatting", "macros", "serde"] } # Date and time handling
hashbrown = { version = "0.15.2", features = ["serde"] } # HashMap and HashSet
indexmap = { version = "2.9.0" } # Ordered HashMap and HashSet

env_logger = { version = "0.11.8" } # Environment variables for the logger
colog = { version = "1.3.0" } # Logger Formatter
log = { version = "0.4.27" } # Logger

serde = { version = "1.0.219", features = ["derive"] } # Serialize and deserialize data
strum = { version = "0.27.1", features = ["derive"] } # Enum utilities
state-shift = { version = "2.1.1" } # Type State Machine
confy = { version = "1.0.0", default-features = false, features = ["ron_conf"] } # Configuration location management
colored = { version = "3.0.0" } # Color strings for the terminal
const_format = { version = "0.2.34" } # Compile-time string formatting
simply_colored = { version = "0.1.0" } # Const colors
anstyle = { version = "1.0.11" } # ANSI style formatting
dialoguer = { version = "0.11.0", features = ["fuzzy-select"] } # Interactive command line dialog
humantime = "2.2.0" # Human readable time

# [build-dependencies]
# clap = { version = "4.5.17", features = ["derive", "cargo"] } # Handles parsing input from command line
# clap_complete = { version = "4.5.26" } # Generates the shell completion to clap commands

[dev-dependencies]
rexpect = { version = "0.6.2" } # Spawn a child process and interact with it
assertables = { version = "9.7.0" } # Assertables test utilities
regex = { version = "1.11.1" } # Regular expressions