[tasks.run]
# Runs in real mode with trace logs.
# Example: `cargo make dryrun git keygen shimi@gmail.com`
command = "cargo"
env = { SHIMI_LOG = "trace" }
args = [
	"run",
	"--",
	"${@}",
]

[tasks.dryrun]
# Runs in dry-run mode with trace logs.
# Example: `cargo make dryrun git keygen shimi@gmail.com`
command = "cargo"
env = { SHIMI_LOG = "trace" }
args = [
	"run",
	"--features", "dry_run",
	"--",
	"${@}",
]

[tasks.editDryRun]
# Changes the current state for dry-run mode.
# Example: `cargo make editDryRun`
command = "cargo"
args = [
	"run",
	"--features", "dry_run",
	"--bin", "edit_orch_dry_run",
]